!----------------------------------------------------------------------------
!     CVS:$Id: adeco_common.F90,v 1.4 2004/12/16 18:45:49 duse Exp $
!     CVS:$Name:  $
!----------------------------------------------------------------------------
module adeco_common
!-------------------------------------------------------------------------
! Code adapted from routines generated by 
! Tangent linear and Adjoint Model Compiler,  TAMC 5.3.2
! Modified by Jeff Dusenberry
!-------------------------------------------------------------------------
!  use grid, only : nz
  implicit none

! save everything
  save

  double precision :: rltb

!  double precision, dimension(nz+1) :: adpar_ifc

end module adeco_common
