!----------------------------------------------------------------------------
!     CVS:$Id: adnumeric_subs.F90,v 1.5 2004/10/18 20:36:28 duse Exp $
!     CVS:$Name:  $
!----------------------------------------------------------------------------
module adnumeric_subs
  !-------------------------------------------------------------------------
  ! Adjoint code (beginning in ad*) adapted from routines generated by the
  ! Tangent linear and Adjoint Model Compiler,  TAMC 5.3.2 and
  ! modified by Jeff Dusenberry
  !-------------------------------------------------------------------------
  implicit none

contains


  subroutine adtridag( a, b, c, n, adr, adu )
    use const, only : c0
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    integer n
    double precision, dimension(:) ::  a,adr,adu,b,c
!    double precision adr(n)
!    double precision adu(n)
!    double precision b(n)
!    double precision c(n)

    !==============================================
    ! define local variables
    !==============================================
    double precision, dimension(n) ::  adbl,adxu,bet,gam
!    double precision adxu(n)
!    double precision bet(n)
!    double precision gam(n)
!    integer ip1
    integer j

    !----------------------------------------------
    ! RESET LOCAL ADJOINT VARIABLES
    !----------------------------------------------
!    do ip1 = 1, n
!       adbl(ip1) = c0
!    end do
!    do ip1 = 1, n
!       adxu(ip1) = c0
!    end do

    adbl = c0
    adxu = c0


    !----------------------------------------------
    ! ROUTINE BODY
    !----------------------------------------------
    bet(1) = b(1)
    do j = 2, n-1
       gam(j) = c(j-1)/bet(j-1)
       bet(j) = b(j)-a(j)*gam(j)
    end do
    j = n
    gam(j) = c(j-1)/bet(j-1)
    do j = 1, n
       adbl(j) = adbl(j)+adu(j)
       adu(j) = c0
    end do
    do j = 1, n-1
       adbl(j) = adbl(j)+adxu(j)
       adxu(j) = c0
       adxu(j+1) = adxu(j+1)-adbl(j)*gam(j+1)
       adxu(j) = adxu(j)+adbl(j)
       adbl(j) = c0
    end do
    adxu(n) = adxu(n)+adbl(n)
    adbl(n) = c0
    bet(1) = b(1)
    do j = 2, n-1
       gam(j) = c(j-1)/bet(j-1)
       bet(j) = b(j)-a(j)*gam(j)
    end do
    do j = n, 2, -1
       gam(j) = c(j-1)/bet(j-1)
       bet(j) = b(j)-a(j)*gam(j)
       adr(j) = adr(j)+adxu(j)/bet(j)
       adxu(j-1) = adxu(j-1)-adxu(j)*(a(j)/bet(j))
       adxu(j) = c0
    end do
    adr(1) = adr(1)+adxu(1)/bet(1)
    adxu(1) = c0

  end subroutine adtridag


end module adnumeric_subs

