!----------------------------------------------------------------------------
!     CVS:$Id: adphysderivs_mod.F90,v 1.14 2005/04/28 17:34:20 duse Exp $
!     CVS:$Name:  $
!----------------------------------------------------------------------------
module adphysderivs_mod
  !-------------------------------------------------------------------------
  ! Adjoint code (beginning in ad*) adapted from routines generated by the
  ! Tangent linear and Adjoint Model Compiler,  TAMC 5.3.2 and
  ! modified by Jeff Dusenberry
  !-------------------------------------------------------------------------
  implicit none

contains

  subroutine adphysderivs(istep,bio_prev,bioparams,adbio_prev,addydt,adbioparams)
    use const, only : c0
    use eco_params, only : numstatevar
    use grid, only : nz
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    double precision, dimension(:,:) :: bio_prev,adbio_prev,addydt
    double precision, dimension(:) :: bioparams,adbioparams
    integer istep

    !==============================================
    ! define local variables
    !==============================================
    double precision addydt_tmp(nz+1,numstatevar)

    !----------------------------------------------
    ! RESET LOCAL ADJOINT VARIABLES
    !----------------------------------------------
    addydt_tmp = c0

    !----------------------------------------------
    ! ROUTINE BODY
    !----------------------------------------------
    addydt_tmp = addydt_tmp+addydt
    call adsink(bio_prev,bioparams,adbio_prev,addydt_tmp,adbioparams)
    addydt_tmp = addydt_tmp+addydt
    call adset_sflux( adbio_prev,addydt_tmp )
    addydt_tmp = addydt_tmp+addydt
    call advertadv(istep,bio_prev,adbio_prev,addydt_tmp)
    addydt_tmp = addydt_tmp+addydt
    call adhorizadv(istep,adbio_prev,addydt_tmp)
    addydt_tmp = addydt_tmp+addydt
    addydt = c0
    call advertmix( istep,adbio_prev,addydt_tmp )

  end subroutine adphysderivs


  subroutine adphysderivs_init(istep,bio_prev,adbio_prev)
    use common_mod, only : bbcnsv,flag_bbcnsv
    use const, only : c0,c1,c2,mc1
    use grid, only : nz
    use eco_params, only : numstatevar
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    double precision, dimension(:,:) ::  bio_prev,adbio_prev
    integer istep 
    !----------------------------------------------
    ! ROUTINE BODY
    !----------------------------------------------
    where (bbcnsv(:,istep) .lt. mc1)
       bio_prev(nz+1,:) = bio_prev(nz,:)- &
            (bio_prev(nz-1,:)-bio_prev(nz,:))
       where (bio_prev(nz+1,:) .lt. c0)
          adbio_prev(nz+1,:) = c0
       endwhere
       adbio_prev(nz-1,:) = adbio_prev(nz-1,:)- &
            adbio_prev(nz+1,:)
       adbio_prev(nz,:) = adbio_prev(nz,:)+ &
            2*adbio_prev(nz+1,:)
       adbio_prev(nz+1,:) = c0
    elsewhere
       where(flag_bbcnsv(:) .eq. c1)
               bio_prev(nz+1,:)=bbcnsv(:,istep-1)
        elsewhere(flag_bbcnsv(:) .ge.c2)
               bio_prev(nz+1,:)=bio_prev(nz,:)+bbcnsv(:,istep-1)
        endwhere
       where (bio_prev(nz+1,:) .lt. c0)
          adbio_prev(nz+1,:) = c0
       endwhere
       where(flag_bbcnsv(:) .eq. c1)
           adbio_prev(nz+1,:) = c0
       elsewhere(flag_bbcnsv(:) .ge.c2)
           adbio_prev(nz,:) = adbio_prev(nz,:) +  adbio_prev(nz+1,:)
           adbio_prev(nz+1,:) = c0
       endwhere
    endwhere
    
  end subroutine adphysderivs_init


  subroutine adset_sflux(adbio_prev,addydt)
    use const, only : c0
    use eco_common, only : aeonsv
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    double precision, dimension(:,:) :: adbio_prev,addydt

    !----------------------------------------------
    ! ROUTINE BODY
    !----------------------------------------------
    where (aeonsv .ne. 0)
       addydt(1,:) = c0
    endwhere
    addydt = c0

  end subroutine adset_sflux


  subroutine adsink( bio_prev, bioparams,adbio_prev, addydt, adbioparams)
    use const, only : c0,c1,c2,rc6,secperday,p5
    use eco_common, only : wnsvflag
    use eco_params, only : numstatevar
    use grid, only : delt,nz,rdzt,rdzv
    use physderivs_mod, only : smalln
    use eco_params, only : iwnsvo
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    double precision, dimension(:,:) ::  adbio_prev,addydt,bio_prev
    double precision, dimension(:) :: bioparams,adbioparams

    !==============================================
    ! define local variables
    !==============================================
    double precision adcfl
double precision add0
double precision add1
double precision adpsi_work
double precision adpsimrj
double precision adpsiprj
double precision adrj
double precision adrjm
double precision adrjp
double precision adwfld
double precision adwflux(nz+1)
double precision adwfluxkp1
double precision adwm
double precision adwnsv(numstatevar)
double precision adwp
double precision cfl
double precision d0
double precision d1
integer ip1
integer isv
integer k
integer km1
integer km2
integer kp1
double precision psi_work
double precision psimrj
double precision psiprj
double precision rj
double precision rjm
double precision rjp
double precision wfld
double precision wflux(nz+1)
double precision wfluxkp1
double precision wm
double precision wnsv(numstatevar)
double precision wp

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
adcfl = 0.d0
add0 = 0.d0
add1 = 0.d0
adpsi_work = 0.d0
adpsimrj = 0.d0
adpsiprj = 0.d0
adrj = 0.d0
adrjm = 0.d0
adrjp = 0.d0
adwfld = 0.d0
do ip1 = 1, nz+1
  adwflux(ip1) = 0.d0
end do
adwfluxkp1 = 0.d0
adwm = 0.d0
do ip1 = 1, numstatevar
  adwnsv(ip1) = 0.d0
end do
adwp = 0.d0

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
!----------------------------------------------
! FUNCTION AND TAPE COMPUTATIONS
!----------------------------------------------
wnsv = bioparams(iwnsvo)*wnsvflag

do isv = 1, numstatevar
  wflux = c0
  wfluxkp1 = c0
  do k = nz+1, 2, -1
    wfld = -(wnsv(isv)/secperday)
    wp = wfld+abs(wfld)
    wm = wfld-abs(wfld)
    kp1 = min(k+1,nz+1)
    km1 = max(k-1,1)
    km2 = max(k-2,1)
    rjp = bio_prev(km2,isv)-bio_prev(km1,isv)
    rj = bio_prev(km1,isv)-bio_prev(k,isv)
    rjm = bio_prev(k,isv)-bio_prev(kp1,isv)
    cfl = abs(wfld*delt*rdzv(k))
    d0 = (c2-cfl)*(c1-cfl)*rc6
    d1 = (c1-cfl*cfl)*rc6
    psiprj = d0*rj+d1*rjm
    psimrj = d0*rj+d1*rjp
    if (rj .gt. c0) then
      if (rj .lt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .lt. psiprj) then
        psiprj = psi_work
      endif
      if (c0 .gt. psiprj) then
        psiprj = c0
      endif
      if (rj .lt. psimrj) then
        psimrj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjp
      if (psi_work .lt. psimrj) then
        psimrj = psi_work
      endif
      if (c0 .gt. psimrj) then
        psimrj = c0
      endif
    else
      if (rj .gt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .gt. psiprj) then
        psiprj = psi_work
      endif
      if (c0 .lt. psiprj) then
        psiprj = c0
      endif
      if (rj .gt. psimrj) then
        psimrj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjp
      if (psi_work .gt. psimrj) then
        psimrj = psi_work
      endif
      if (c0 .lt. psimrj) then
        psimrj = c0
      endif
    endif
    wflux(k) = 0.5*wp*(bio_prev(k,isv)+psiprj)+0.5*wm*(bio_prev(km1,isv)-psimrj)

    wfluxkp1 = wflux(k)
  end do
  k = 1
  wflux(k) = c0

end do

!----------------------------------------------
! ADJOINT COMPUTATIONS
!----------------------------------------------
do isv = numstatevar, 1, -1
  k = 1
  adwflux(k) = adwflux(k)-addydt(k,isv)*rdzt(k)
  adwfluxkp1 = adwfluxkp1+addydt(k,isv)*rdzt(k)
  addydt(k,isv) = 0.d0
  adwflux(k) = 0.d0
  do k = 2, nz+1
    wfld = -(wnsv(isv)/secperday)
    wp = wfld+abs(wfld)
    wm = wfld-abs(wfld)
    kp1 = min(k+1,nz+1)
    km1 = max(k-1,1)
    km2 = max(k-2,1)
    rjp = bio_prev(km2,isv)-bio_prev(km1,isv)
    rj = bio_prev(km1,isv)-bio_prev(k,isv)
    rjm = bio_prev(k,isv)-bio_prev(kp1,isv)
    cfl = abs(wfld*delt*rdzv(k))
    d0 = (c2-cfl)*(c1-cfl)*rc6
    d1 = (c1-cfl*cfl)*rc6
    psiprj = d0*rj+d1*rjm
    psimrj = d0*rj+d1*rjp
    if (rj .gt. c0) then
      if (rj .lt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .lt. psiprj) then
        psiprj = psi_work
      endif
      if (c0 .gt. psiprj) then
        psiprj = c0
      endif
      if (rj .lt. psimrj) then
        psimrj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjp
      if (psi_work .lt. psimrj) then
        psimrj = psi_work
      endif
      if (c0 .gt. psimrj) then
        psimrj = c0
      endif
    else
      if (rj .gt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .gt. psiprj) then
        psiprj = psi_work
      endif
      if (c0 .lt. psiprj) then
        psiprj = c0
      endif
      if (rj .gt. psimrj) then
        psimrj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjp
      if (psi_work .gt. psimrj) then
        psimrj = psi_work
      endif
      if (c0 .lt. psimrj) then
        psimrj = c0
      endif
    endif
    adwflux(k) = adwflux(k)+adwfluxkp1
    adwfluxkp1 = 0.d0
    if (k .le. nz) then
      adwflux(k) = adwflux(k)-addydt(k,isv)*rdzt(k)
      adwfluxkp1 = adwfluxkp1+addydt(k,isv)*rdzt(k)
      addydt(k,isv) = 0.d0
    endif
    adbio_prev(k,isv) = adbio_prev(k,isv)+0.5*adwflux(k)*wp
    adbio_prev(km1,isv) = adbio_prev(km1,isv)+0.5*adwflux(k)*wm
    adpsimrj = adpsimrj-0.5*adwflux(k)*wm
    adpsiprj = adpsiprj+0.5*adwflux(k)*wp
    adwm = adwm+0.5*adwflux(k)*(bio_prev(km1,isv)-psimrj)
    adwp = adwp+0.5*adwflux(k)*(bio_prev(k,isv)+psiprj)
    adwflux(k) = 0.d0
    if (rj .gt. c0) then
      psimrj = d0*rj+d1*rjp
      if (rj .lt. psimrj) then
        psimrj = rj
      endif
      if (psi_work .lt. psimrj) then
        psimrj = psi_work
      endif
      if (c0 .gt. psimrj) then
        adpsimrj = 0.d0
      endif
      psimrj = d0*rj+d1*rjp
      if (rj .lt. psimrj) then
        psimrj = rj
      endif
      if (psi_work .lt. psimrj) then
        adpsi_work = adpsi_work+adpsimrj
        adpsimrj = 0.d0
      endif
      adcfl = adcfl+adpsi_work*((-1)/(smalln+cfl)-(c1-cfl)/((smalln+cfl)*(smalln+cfl)))*rjp
      adrjp = adrjp+adpsi_work*((c1-cfl)/(smalln+cfl))
      adpsi_work = 0.d0
      psimrj = d0*rj+d1*rjp
      if (rj .lt. psimrj) then
        adrj = adrj+adpsimrj
        adpsimrj = 0.d0
      endif
      psiprj = d0*rj+d1*rjm
      if (rj .lt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .lt. psiprj) then
        psiprj = psi_work
      endif
      if (c0 .gt. psiprj) then
        adpsiprj = 0.d0
      endif
      psiprj = d0*rj+d1*rjm
      if (rj .lt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .lt. psiprj) then
        adpsi_work = adpsi_work+adpsiprj
        adpsiprj = 0.d0
      endif
      adcfl = adcfl+adpsi_work*((-1)/(smalln+cfl)-(c1-cfl)/((smalln+cfl)*(smalln+cfl)))*rjm
      adrjm = adrjm+adpsi_work*((c1-cfl)/(smalln+cfl))
      adpsi_work = 0.d0
      psiprj = d0*rj+d1*rjm
      if (rj .lt. psiprj) then
        adrj = adrj+adpsiprj
        adpsiprj = 0.d0
      endif
    else
      psimrj = d0*rj+d1*rjp
      if (rj .gt. psimrj) then
        psimrj = rj
      endif
      if (psi_work .gt. psimrj) then
        psimrj = psi_work
      endif
      if (c0 .lt. psimrj) then
        adpsimrj = 0.d0
      endif
      psimrj = d0*rj+d1*rjp
      if (rj .gt. psimrj) then
        psimrj = rj
      endif
      if (psi_work .gt. psimrj) then
        adpsi_work = adpsi_work+adpsimrj
        adpsimrj = 0.d0
      endif
      adcfl = adcfl+adpsi_work*((-1)/(smalln+cfl)-(c1-cfl)/((smalln+cfl)*(smalln+cfl)))*rjp
      adrjp = adrjp+adpsi_work*((c1-cfl)/(smalln+cfl))
      adpsi_work = 0.d0
      psimrj = d0*rj+d1*rjp
      if (rj .gt. psimrj) then
        adrj = adrj+adpsimrj
        adpsimrj = 0.d0
      endif
      psiprj = d0*rj+d1*rjm
      if (rj .gt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .gt. psiprj) then
        psiprj = psi_work
      endif
      if (c0 .lt. psiprj) then
        adpsiprj = 0.d0
      endif
      psiprj = d0*rj+d1*rjm
      if (rj .gt. psiprj) then
        psiprj = rj
      endif
      psi_work = (c1-cfl)/(smalln+cfl)*rjm
      if (psi_work .gt. psiprj) then
        adpsi_work = adpsi_work+adpsiprj
        adpsiprj = 0.d0
      endif
      adcfl = adcfl+adpsi_work*((-1)/(smalln+cfl)-(c1-cfl)/((smalln+cfl)*(smalln+cfl)))*rjm
      adrjm = adrjm+adpsi_work*((c1-cfl)/(smalln+cfl))
      adpsi_work = 0.d0
      psiprj = d0*rj+d1*rjm
      if (rj .gt. psiprj) then
        adrj = adrj+adpsiprj
        adpsiprj = 0.d0
      endif
    endif
    add0 = add0+adpsimrj*rj
    add1 = add1+adpsimrj*rjp
    adrj = adrj+adpsimrj*d0
    adrjp = adrjp+adpsimrj*d1
    adpsimrj = 0.d0
    add0 = add0+adpsiprj*rj
    add1 = add1+adpsiprj*rjm
    adrj = adrj+adpsiprj*d0
    adrjm = adrjm+adpsiprj*d1
    adpsiprj = 0.d0
    adcfl = adcfl-2*add1*cfl*rc6
    add1 = 0.d0
    adcfl = adcfl-add0*(c2-cfl+c1-cfl)*rc6
    add0 = 0.d0
    adwfld = adwfld+adcfl*delt*rdzv(k)*sign(1.d0,wfld*delt*rdzv(k))
    adcfl = 0.d0
    adbio_prev(k,isv) = adbio_prev(k,isv)+adrjm
    adbio_prev(kp1,isv) = adbio_prev(kp1,isv)-adrjm
    adrjm = 0.d0
    adbio_prev(k,isv) = adbio_prev(k,isv)-adrj
    adbio_prev(km1,isv) = adbio_prev(km1,isv)+adrj
    adrj = 0.d0
    adbio_prev(km1,isv) = adbio_prev(km1,isv)-adrjp
    adbio_prev(km2,isv) = adbio_prev(km2,isv)+adrjp
    adrjp = 0.d0
    adwfld = adwfld+adwm*(1-sign(1.d0,wfld))
    adwm = 0.d0
    adwfld = adwfld+adwp*(1+sign(1.d0,wfld))
    adwp = 0.d0
    adwnsv(isv) = adwnsv(isv)-adwfld/secperday
    adwfld = 0.d0
  end do
  adwfluxkp1 = 0.d0
  adwflux = 0.d0
end do
adbioparams(iwnsvo) = adbioparams(iwnsvo)+sum(adwnsv*wnsvflag)
adwnsv = 0.d0


  end subroutine adsink


  subroutine adhorizadv( istep, adbio_prev, addydt )
    use common_mod, only : horiz_adv,lhoriz_adv
    use const, only : c0
    use grid, only : nz
    use physderivs_mod, only : hadv_wt
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    double precision, dimension(:,:) ::  adbio_prev, addydt
    integer istep

    !==============================================
    ! define local variables
    !==============================================
    integer iz

    !----------------------------------------------
    ! ROUTINE BODY
    !----------------------------------------------
    do iz = nz, 16, -1
       where (lhoriz_adv)
          adbio_prev(iz,:) = adbio_prev(iz,:)-addydt(iz,:)*hadv_wt* &
               horiz_adv(iz,:,istep)
          addydt(iz,:) = c0
       endwhere
    end do
    addydt = c0

  end subroutine adhorizadv



  subroutine advertadv( istep, bio_prev, adbio_prev, addydt )
    use const, only : c0,c1,c2,rc6,secperday,p5
    use eco_params, only : numstatevar
    use forcing, only : wvel
    use grid, only : delt,nz,rdzt,rdzv
    use physderivs_mod, only : smalln
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    double precision adbio_prev(:,:)
    double precision addydt(:,:)
    double precision bio_prev(:,:)
    integer istep

    !==============================================
    ! define local variables
    !==============================================
    double precision adpsi_work
    double precision adpsimrj
    double precision adpsiprj
    double precision adrj
    double precision adrjm
    double precision adrjp
    double precision adwflux(nz+1)
    double precision adwfluxkp1
    double precision cfl
    double precision d0
    double precision d1
    integer isv
    integer k
    integer km1
    integer km2
    integer kp1
    double precision psi_work
    double precision psimrj
    double precision psiprj
    double precision rj
    double precision rjm
    double precision rjp
    double precision wfld
    double precision wm
    double precision wp

    !----------------------------------------------
    ! RESET LOCAL ADJOINT VARIABLES
    !----------------------------------------------
    adpsi_work = c0
    adpsimrj = c0
    adpsiprj = c0
    adrj = c0
    adrjm = c0
    adrjp = c0
    adwflux = c0
    adwfluxkp1 = c0

    !----------------------------------------------
    ! ROUTINE BODY
    !----------------------------------------------
    do isv = 1, numstatevar
       adpsi_work = c0
       adpsimrj = c0
       adpsiprj = c0
       adrj = c0
       adrjm = c0
       adrjp = c0
       adwfluxkp1 = c0
       do k = 1, nz+1
          wfld = -wvel(k,istep)
          wp = wfld+abs(wfld)
          wm = wfld-abs(wfld)
          kp1 = min(k+1,nz+1)
          km1 = max(k-1,1)
          km2 = max(k-2,1)
          rjp = bio_prev(km2,isv)-bio_prev(km1,isv)
          rj = bio_prev(km1,isv)-bio_prev(k,isv)
          rjm = bio_prev(k,isv)-bio_prev(kp1,isv)
          cfl = abs(wfld*delt*rdzv(k))
          d0 = (c2-cfl)*(c1-cfl)*rc6
          d1 = (c1-cfl*cfl)*rc6
          psiprj = d0*rj+d1*rjm
          psimrj = d0*rj+d1*rjp
          adwflux(k) = adwflux(k)+adwfluxkp1
          adwfluxkp1 = c0
          if (k .le. nz) then
             adbio_prev(k,isv) = adbio_prev(k,isv)+ &
                  addydt(k,isv)*(wvel(kp1,istep)-wvel(k,istep))*rdzt(k)
             adwflux(k) = adwflux(k)-addydt(k,isv)*rdzt(k)
             adwfluxkp1 = adwfluxkp1+addydt(k,isv)*rdzt(k)
             addydt(k,isv) = c0
          endif
          adbio_prev(k,isv) = adbio_prev(k,isv)+p5*adwflux(k)*wp
          adbio_prev(km1,isv) = adbio_prev(km1,isv)+p5*adwflux(k)*wm
          adpsimrj = adpsimrj-p5*adwflux(k)*wm
          adpsiprj = adpsiprj+p5*adwflux(k)*wp
          adwflux(k) = c0
          if (rj .gt. c0) then
             if (rj .lt. psiprj) then
                psiprj = rj
             endif
             psi_work = (c1-cfl)/(smalln+cfl)*rjm
             if (psi_work .lt. psiprj) then
                psiprj = psi_work
             endif
             if (rj .lt. psimrj) then
                psimrj = rj
             endif
             psi_work = (c1-cfl)/(smalln+cfl)*rjp
             if (psi_work .lt. psimrj) then
                psimrj = psi_work
             endif
             if (c0 .gt. psimrj) then
                adpsimrj = c0
             endif
             psimrj = d0*rj+d1*rjp
             if (rj .lt. psimrj) then
                psimrj = rj
             endif
             if (psi_work .lt. psimrj) then
                adpsi_work = adpsi_work+adpsimrj
                adpsimrj = c0
             endif
             adrjp = adrjp+adpsi_work*((c1-cfl)/(smalln+cfl))
             adpsi_work = c0
             psimrj = d0*rj+d1*rjp
             if (rj .lt. psimrj) then
                adrj = adrj+adpsimrj
                adpsimrj = c0
             endif
             if (c0 .gt. psiprj) then
                adpsiprj = c0
             endif
             psiprj = d0*rj+d1*rjm
             if (rj .lt. psiprj) then
                psiprj = rj
             endif
             psi_work = (c1-cfl)/(smalln+cfl)*rjm
             if (psi_work .lt. psiprj) then
                adpsi_work = adpsi_work+adpsiprj
                adpsiprj = c0
             endif
             adrjm = adrjm+adpsi_work*((c1-cfl)/(smalln+cfl))
             adpsi_work = c0
             psiprj = d0*rj+d1*rjm
             if (rj .lt. psiprj) then
                adrj = adrj+adpsiprj
                adpsiprj = c0
             endif
          else
             if (rj .gt. psiprj) then
                psiprj = rj
             endif
             psi_work = (c1-cfl)/(smalln+cfl)*rjm
             if (psi_work .gt. psiprj) then
                psiprj = psi_work
             endif
             if (rj .gt. psimrj) then
                psimrj = rj
             endif
             psi_work = (c1-cfl)/(smalln+cfl)*rjp
             if (psi_work .gt. psimrj) then
                psimrj = psi_work
             endif
             if (c0 .lt. psimrj) then
                adpsimrj = c0
             endif
             psimrj = d0*rj+d1*rjp
             if (rj .gt. psimrj) then
                psimrj = rj
             endif
             if (psi_work .gt. psimrj) then
                adpsi_work = adpsi_work+adpsimrj
                adpsimrj = c0
             endif
             adrjp = adrjp+adpsi_work*((c1-cfl)/(smalln+cfl))
             adpsi_work = c0
             psimrj = d0*rj+d1*rjp
             if (rj .gt. psimrj) then
                adrj = adrj+adpsimrj
                adpsimrj = c0
             endif
             if (c0 .lt. psiprj) then
                adpsiprj = c0
             endif
             psiprj = d0*rj+d1*rjm
             if (rj .gt. psiprj) then
                psiprj = rj
             endif
             psi_work = (c1-cfl)/(smalln+cfl)*rjm
             if (psi_work .gt. psiprj) then
                adpsi_work = adpsi_work+adpsiprj
                adpsiprj = c0
             endif
             adrjm = adrjm+adpsi_work*((c1-cfl)/(smalln+cfl))
             adpsi_work = c0
             psiprj = d0*rj+d1*rjm
             if (rj .gt. psiprj) then
                adrj = adrj+adpsiprj
                adpsiprj = c0
             endif
          endif
          adrj = adrj+adpsimrj*d0
          adrjp = adrjp+adpsimrj*d1
          adpsimrj = c0
          adrj = adrj+adpsiprj*d0
          adrjm = adrjm+adpsiprj*d1
          adpsiprj = c0
          adbio_prev(k,isv) = adbio_prev(k,isv)+adrjm
          adbio_prev(kp1,isv) = adbio_prev(kp1,isv)-adrjm
          adrjm = c0
          adbio_prev(k,isv) = adbio_prev(k,isv)-adrj
          adbio_prev(km1,isv) = adbio_prev(km1,isv)+adrj
          adrj = c0
          adbio_prev(km1,isv) = adbio_prev(km1,isv)-adrjp
          adbio_prev(km2,isv) = adbio_prev(km2,isv)+adrjp
          adrjp = c0
       end do
       adwfluxkp1 = c0
       adwflux = c0
    end do
    addydt = c0

  end subroutine advertadv


  subroutine advertmix(istep,adbio_prev,addydt)
    use adnumeric_subs, only : adtridag
    use eco_params, only : numstatevar
    use const, only : c0,c1,c2,p5
    use forcing, only : rkz
    use grid, only : delt,dzt,nz,zmid
    implicit none

    !==============================================
    ! define arguments
    !==============================================
    double precision,dimension(:,:) ::  adbio_prev,addydt
    integer istep

    !==============================================
    ! define local variables
    !==============================================
    double precision adbio_new(nz)
    double precision adrr(nz)
    integer isv
    integer iz
    double precision tria(nz)
    double precision trib(nz)
    double precision tric(nz)

    !----------------------------------------------
    ! RESET LOCAL ADJOINT VARIABLES
    !----------------------------------------------
    adbio_new = c0
    adrr = c0

    !----------------------------------------------
    ! ROUTINE BODY
    !----------------------------------------------
    iz = 1
    tria(iz) = c0
    tric(iz) = -(p5*delt*rkz(iz+1,istep)/(zmid(iz+1)-zmid(iz))/dzt(iz))
    trib(iz) = c1-tric(iz)
    do iz = 2, nz
       tria(iz) = -(p5*delt*rkz(iz,istep)/(zmid(iz)-zmid(iz-1))/dzt(iz))
       tric(iz) = -(p5*delt*rkz(iz+1,istep)/(zmid(iz+1)-zmid(iz))/dzt(iz))
       trib(iz) = c1-tria(iz)-tric(iz)
    end do
    trib(nz) = c1-tria(nz)
    do isv = numstatevar, 1, -1
       do iz = 1, nz
          adbio_new(iz) = adbio_new(iz)+addydt(iz,isv)/delt
          adbio_prev(iz,isv) = adbio_prev(iz,isv)-addydt(iz,isv)/delt
          addydt(iz,isv) = c0
       end do
       call adtridag( tria,trib,tric,nz,adrr,adbio_new )
       adbio_prev(nz-1,isv) = adbio_prev(nz-1,isv)+ &
            adrr(nz)*p5*delt/(zmid(nz)-zmid(nz-1))/ &
            dzt(nz)*rkz(nz,istep)
       adbio_prev(nz+1,isv) = adbio_prev(nz+1,isv)+ &
            adrr(nz)*delt/(zmid(nz+1)-zmid(nz))/ &
            dzt(nz)*rkz(nz+1,istep)
       adbio_prev(nz,isv) = adbio_prev(nz,isv)+ &
            adrr(nz)*(1-p5*delt/(zmid(nz)-zmid(nz-1))/ &
            dzt(nz)*rkz(nz,istep)-delt/(zmid(nz+1)-zmid(nz))/ &
            dzt(nz)*rkz(nz+1,istep))
       adrr(nz) = c0
       do iz = 2, nz-1
          adbio_prev(iz-1,isv) = adbio_prev(iz-1,isv)+adrr(iz)*p5*delt/ &
               (zmid(iz)-zmid(iz-1))/dzt(iz)*rkz(iz,istep)
          adbio_prev(iz+1,isv) = adbio_prev(iz+1,isv)+adrr(iz)*p5*delt/ &
               (zmid(iz+1)-zmid(iz))/dzt(iz)*rkz(iz+1,istep)
          adbio_prev(iz,isv) = adbio_prev(iz,isv)+adrr(iz)*(1-p5*delt/ &
               (zmid(iz)-zmid(iz-1))/dzt(iz)*rkz(iz,istep)-p5*delt/ &
               (zmid(iz+1)-zmid(iz))/dzt(iz)*rkz(iz+1,istep))
          adrr(iz) = c0
       end do
       iz = 1
       adbio_prev(iz+1,isv) = adbio_prev(iz+1,isv)+adrr(iz)*p5*delt/ &
            (zmid(iz+1)-zmid(iz))/dzt(iz)*rkz(iz+1,istep)
       adbio_prev(iz,isv) = adbio_prev(iz,isv)+adrr(iz)*(1-p5*delt/ &
            (zmid(iz+1)-zmid(iz))/dzt(iz)*rkz(iz+1,istep))
       adrr(iz) = c0
    end do

  end subroutine advertmix


end module adphysderivs_mod
